name: Build Status

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node.js Environment Setup
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup yarn
        run: |
          corepack enable
          yarn set version stable

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build
